/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloIsland: typeof import('./components/HelloIsland/HelloIsland.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher/LanguageSwitcher.vue')['default']
    ThemeSettings: typeof import('./components/ThemeSettings/ThemeSettings.vue')['default']
  }
}
